name: homer_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _r-mutex=1.0.1
  - alabaster=1.0.0
  - alsa-lib=1.2.14
  - babel=2.17.0
  - bedtools=2.31.1
  - binutils_impl_linux-64=2.44
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bwa=0.7.19
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cairo=1.18.0
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - contourpy=1.3.2
  - curl=8.17.0
  - cutadapt=5.2
  - cycler=0.12.1
  - deeptools=3.5.6
  - deeptoolsintervals=0.1.9
  - dnaio=1.2.2
  - docutils=0.21.2
  - expat=2.7.3
  - fastqc=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc_impl_linux-64=15.2.0
  - gfortran_impl_linux-64=15.2.0
  - giflib=5.2.2
  - graphite2=1.3.14
  - gxx_impl_linux-64=15.2.0
  - h2=4.3.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - htslib=1.21
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - isa-l=2.31.1
  - jinja2=3.1.6
  - kernel-headers_linux-64=6.12.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcups=2.3.3
  - libcurl=8.17.0
  - libdeflate=1.20
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.80.2
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsanitizer=15.2.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - make=4.4.1
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - munkres=1.1.4
  - narwhals=2.12.0
  - ncbi-vdb=3.2.1
  - ncurses=6.5
  - numpy=2.2.6
  - numpydoc=1.9.0
  - openjdk=23.0.2
  - openjpeg=2.5.2
  - openssl=3.6.0
  - ossuuid=1.6.2
  - packaging=25.0
  - pango=1.54.0
  - pbzip2=1.1.13
  - pcre2=10.43
  - perl=5.32.1
  - perl-alien-build=2.84
  - perl-alien-libxml2=0.17
  - perl-business-isbn=3.007
  - perl-business-isbn-data=20210112.006
  - perl-capture-tiny=0.48
  - perl-carp=1.50
  - perl-constant=1.33
  - perl-exporter=5.74
  - perl-extutils-makemaker=7.70
  - perl-ffi-checklib=0.28
  - perl-file-chdir=0.1011
  - perl-file-path=2.18
  - perl-file-temp=0.2304
  - perl-file-which=1.24
  - perl-importer=0.026
  - perl-parent=0.243
  - perl-path-tiny=0.124
  - perl-pathtools=3.75
  - perl-scope-guard=0.21
  - perl-sub-info=0.002
  - perl-term-table=0.027
  - perl-test-fatal=0.016
  - perl-test-warnings=0.031
  - perl-test2-suite=0.000163
  - perl-try-tiny=0.31
  - perl-uri=5.34
  - perl-xml-libxml=2.0210
  - perl-xml-namespacesupport=1.12
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - picard=3.4.0
  - pigz=2.8
  - pillow=10.4.0
  - pip=25.3
  - pixman=0.46.4
  - plotly=6.5.0
  - pthread-stubs=0.3
  - py2bit=0.3.3
  - pybigwig=0.3.24
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysam=0.22.1
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-isal=1.8.0
  - python-zlib-ng=1.0.0
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - r-base=4.4.1
  - readline=8.3
  - requests=2.32.5
  - samtools=1.21
  - scipy=1.15.2
  - sed=4.9
  - setuptools=80.9.0
  - six=1.17.0
  - snowballstemmer=3.0.1
  - sphinx=8.1.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.51.0
  - sra-tools=3.2.1
  - sysroot_linux-64=2.39
  - tk=8.6.15
  - tktable=2.10
  - tomli=2.3.0
  - trim-galore=0.6.10
  - tzdata=2025b
  - unicodedata2=17.0.0
  - urllib3=2.5.0
  - wget=1.21.4
  - wheel=0.45.1
  - xopen=2.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: /home/shobita/miniconda3/envs/homer_env
